### ISSUE TITLE
backbox variables

### ISSUE THREAD

**Issue by Lantoshi** [stdLemon/nostale-auth#2]
Hello again, mate
I have another question.

Do you maybe know what are encoded values of "plugins", "fonts", "audioC", "analyser", "video", "audio", "media", "permissions" and "webglFP"?
I checked and it seems to be sha256 hash. I've been trying to decrypt at least one of them but all sha256 hash databases doesn't have these values.
I've been searching for registry and trying to encode some values of video & audio card to check if encoded string matches values from blackbox...but I couldn't find it.

I would need help with it because I would like to randomize them.

Thanks for any help in advance.
Greetings

**Comment by Lantoshi** [comment]
I've checked game1.js file and tried to deobfuscate it.
I found 


> 'v': VERSION,
>             'tz': Intl[_0x116980(0x1d4)]()[_0x116980(0x23e)]()[_0x116980(0x29a)],
>             'dnt': navigator[_0x116980(0x259)] || ![],
>             'product': getBrowserEngine(_0x59a282[_0x116980(0x255)]),
>             'osType': _0x2c9159[_0x116980(0x255)],
>             'app': _0x59a282['name'],
>             'vendor': navigator[_0x116980(0x278)],
>             'cookies': navigator[_0x116980(0x272)],
>             'mem': navigator[_0x116980(0x260)],
>             'con': navigator[_0x116980(0x1c4)],
>             'lang': navigator[_0x116980(0x203)]['join'](','),
>             'plugins': sha256J(getInstalledPlugins()),
>             'gpu': _0x247340['vendor'] + ',' + _0x247340[_0x116980(0x1a4)],
>             'fonts': _0x3d671f,
>             'audioC': sha256J(getAudioContextData()),
>             'analyser': sha256J(getFrequencyAnalyzerData()),
>             'osVersion': _0x2c9159['version'],
>             'width': window[_0x116980(0x1a7)][_0x116980(0x1b7)],
>             'height': window['screen']['availHeight'],
>             'depth': window[_0x116980(0x1a7)][_0x116980(0x20c)],
>             'lStore': Boolean(localStorage),
>             'sStore': Boolean(sessionStorage),
>             'video': sha256J(getSupportedVideoFormats()),
>             'audio': sha256J(getSupportedAudioFormats()),
>             'media': sha256J(_0x4768a2[0x1]),
>             'permissions': sha256J(_0x4768a2[0x0]),
>             'audioFP': _0x4768a2[0x2],
>             'webglFP': _0x5bef7c,
>             'canvasFP': _0x2d7fbb,
>             'dP': _0x306ac0 - _0x26d37a,
>             'dF': _0x12b455 - _0x306ac0,
>             'dW': _0x21c43c - _0x12b455,
>             'dC': _0x3b08b4 - _0x21c43c
> 

and

> const _0x59a282 = getBrowserInfo(),
>             _0x2c9159 = getPlatformInfo(),
>             _0x247340 = getGpuRendererInfo(),
>             _0x4768a2 = await Promise[_0x116980(0x273)]([getPermissions(), getMediaDevices(), getAudioFingerprint()]);
> 

I am not completely sure but I think most of these variables will be the same for every player.
Like browser -> gameforge uses chrome but I think it's going to be const of some special gameforge in-built chrome version.

am I right?

In your point of view which values can be changable in PC?
I would like to use multiple accounts (not connected at one time) to bot minigames. I think I got banned because gameforge checks one of these variables. Some time ago I've never been banned because changing uuid was enough. now it seems like uuid is not the only one variable they are checking.

thanks for any help in advance

**Comment by Lantoshi** [comment]
I just tried to collect blackboxes from multiple PCs.
Most of the values are the same.
Values that changes between PCs:

> audioC
> media
> webglFP
> vector

In your point of view is it possible to modify these values by changing registry or using some spoofers? 
thanks for help in advance

**Comment by stdLemon** [comment]
From what I can see, more values seem to vary. In addition to yours, `fonts` and `canvasFP` fields are also changing.
The vector field is already randomized while generating a new identity.

Getting an input value of a hash is impossible without brute-forcing, so the GF backend isn't reading it.
That's why the simplest way is to generate a Sha256 hash from a random alphanumeric text.

If you want a more accurate way of generating these fingerprints, I don't see any other way than just reversing the `game1.js` file.
You could start by embedding the script into a simple webpage and getting rid of the Sha256J function. Then you'll need to call `game1(console.log)` from the developer's console and decode a received blackbox.

1. index.html
```html
<html>
<script src="game1.js"></script>
</html>
```

2. game1.js
```js
//sha256J = _0x57231b => sha256(JSON[a0_0x5535(0x292)](_0x57231b)),
sha256J = x => x,
```

3. http server
```
python -m http.server
```
