### ISSUE TITLE
Blackbox stopped working

### ISSUE THREAD

**Issue by Hawnsee** [stdLemon/nostale-auth#4]
Hi, hope everythings well. The blackbox atributes has changed and therefore your script is not working anymore. Iovation now returns a blackbox without the 'dP', 'dF', 'dW' and 'dC' values, but keeps the 'd' value. Maybe now we dont need to get the min and max values from 'dP', 'dF', 'dW' and 'dC' and use only that 'd' value. They have also removed the 'cookies' and 'analyser' indexes from the blackbox. 

Also, we need to get a 3 new blackboxes with fiddler after a short period of time, otherwise call to thin/codes returns 403.

Theres any chance you could fix it? Thanks!

**Comment by stdLemon** [comment]
Hi, the black box version has been changed from 7 to 8, thus the content varies.

I'll look into it :)
